### PR TITLE
Update for Anki 2.1.47

### PR DESCRIPTION
**Pull request by RisingOrange**

### CODE REVIEW

**Comment by RisingOrange** [comment]
Is it okay if I upload the udpated version to AnkiWeb?

**Comment by AlienFever** [comment]
Yes of course ! Please do.
Thank you for your contribution.
________________________________

**Comment by RisingOrange** [comment]
Thanks!

**Comment by AlienFever** [comment]
Please send me the link when you upload it so I put a link to it in the original addon post.
________________________________

**Comment by RisingOrange** [comment]
Ok, will do!

**Comment by AnKingMed** [comment]
@AlienFever in the past Damien has been willing to just transfer AnkiWeb listings to me.  Do you have interest in still maintaining your version?  We can just upload it as a separate listing or if you'd prefer you can just transfer the github repo and ankiweb repo (via damien) to me and we can have AnkiPalace maintain it moving forward. I'm more than happy to do whatever, just don't want to step on your toes inappropriately!   (@RisingOrange has been working with me on this update)

**Comment by AlienFever** [comment]
Sure thing !
Yes I can't maintain my version.
I will transfer ownership to you and you can make all appropriate changes and maintain it.

**Comment by AlienFever** [comment]
I just sent the transfer request.
On a side note, I would appreciate it if you could notify me when you release it back to the public ☺️🙏🏻

**Comment by AnKingMed** [comment]
I think we're planning on just leaving it public since it already is :)

**Pull request merged**
